### DISCUSSION TITLE
Permissions Error on Container?

### DISCUSSION THREAD

**Discussion by UnPossible-Me** [jlesage/docker-czkawka#26] [Q&A] [answered]
Hello, 
I'm running around in circles trying to figure out what's going wrong here, could someone please chip in?

My `docker compose` file:
```
version: '3'
services:
  czkawka:
    image: jlesage/czkawka
    ports:
      - "5800:5800"
    volumes:
      - "./config:/config:rw"
      - "/mnt/HDD1/nextcloud:/storage:rw"
    environment:
      - PUID=33  
      - PGID=33
    privileged: true
```

I'm trying to access a directory `/mnt/HDD1/nextcloud` on my external drive.
It has permissions `0770` and `www-data:www-data`

The `uid` and `gid` of `www-data` are correct, I've doubled checked to make sure. and I've also tried running it as `root` i.e. `0:0`

No matter what, czkawka always returns some sort of permission denied message on trying to access it.

However, if I try to use the docker shell:
```
sudo docker exec -ti container sh
```
I'm able to access and manipulate the files just fine.
