### ISSUE TITLE
UI does not show up, container terminates

### ISSUE THREAD

**Issue by chbndrhnns** [jlesage/docker-czkawka#12]
Hi, 

Starting with version v22.11.1, I see a strange behaviour that I am unable to debug further. When I access the app in the browser, it crashes. The logs just contain these lines and setting the `CONTAINER_DEBUG` variable to see more details does not create more verbose output.

Any idea what I could try?

Bye,
Jo

```
czkawka_1  | [app         ] Gdk-Message: 20:24:22.270: Failed to get file transfer portal: Could not connect: No such file or directory
czkawka_1  | [supervisor  ] service 'app' exited (with status 1).
czkawka_1  | [supervisor  ] waiting termination of logger thread of service 'app'...
czkawka_1  | [supervisor  ] logger thread of service 'app' successfully terminated.
czkawka_1  | [supervisor  ] restarting service 'app'.
czkawka_1  | [supervisor  ] starting service 'app'...
czkawka_1  | [supervisor  ] started service 'app'.
czkawka_1  | [supervisor  ] service 'app' exited (with status 1).
czkawka_1  | [supervisor  ] waiting termination of logger thread of service 'app'...
czkawka_1  | [supervisor  ] logger thread of service 'app' successfully terminated.
czkawka_1  | [supervisor  ] restarting service 'app'.
czkawka_1  | [supervisor  ] starting service 'app'...
czkawka_1  | [supervisor  ] started service 'app'.
czkawka_1  | [app         ] Gdk-Message: 20:24:29.373: Failed to get file transfer portal: Could not connect: No such file or directory
czkawka_1  | [supervisor  ] service 'app' exited (with status 1).
czkawka_1  | [supervisor  ] waiting termination of logger thread of service 'app'...
czkawka_1  | [supervisor  ] logger thread of service 'app' successfully terminated.
czkawka_1  | [supervisor  ] restarting service 'app'.
czkawka_1  | [supervisor  ] starting service 'app'...
czkawka_1  | [supervisor  ] started service 'app'.
czkawka_1  | [app         ] Gdk-Message: 20:24:31.275: Failed to get file transfer portal: Could not connect: No such file or directory
```

**Comment by jlesage** [comment]
How did you created the container (your `docker run` command) ?

**Comment by chbndrhnns** [comment]
I am using this docker-compose file:

```yaml
version: '3.1'

services:
  czkawka:
    restart: unless-stopped
    image: jlesage/czkawka:v22.11.1
    environment:
      USER_ID: 1027
      GROUP_ID: 101
      SUP_GROUP_IDS: 100,105733
      CONTAINER_DEBUG: 1
    volumes:
      - ./data/config:/config:rw
      - /volume1/photo/isa+jo:/storage/volume1/photo/isa+jo:rw
      - /volume1/photo/MobileBackup:/storage/volume1/photo/MobileBackup:rw
      - /volume1/photo/zz-testing:/storage/volume1/photo/zz-testing:rw
      - /volume1/database:/storage/volume1/database:rw
      - /volume1/homes/isa:/storage/volume1/homes/isa:rw
      - /volume1/homes/jo:/storage/volume1/homes/jo:rw
    ports:
      - "5800:5800"

```
