### ISSUE TITLE
Manual for QNAP

### ISSUE THREAD

**Issue by domibln** [jlesage/docker-czkawka#31]
### Idea

It took me quite a while to make docker-czkawka run on my new QNAP NAS. You might want to add a short manual to the documentation:

1) Install the Container Station app in the web interface.
2) Open it.
3) Open the 'applications' tab and choose 'create'.
4) Enter a name, e.g. 'czkawka'.
5) Paste the following text into the TEXTAREA:
```
version: '3'
services:
  czkawka:
    image: jlesage/czkawka
    ports:
      - "5800:5800"
    environment:
     - USER_ID=1001
     - GROUP_ID=100
    volumes:
      - "/docker/appdata/czkawka:/config:rw"
      - "/share/CACHEDEV1_data:/storage:rw"
```
You might have to adapt USER_ID and GROUP ID. You will find your **user id** by looking at a user's profile under 'Control Panel' > 'Privilege' > 'Users', the **group id** can be found under 'Control Panel' > 'Privilege' > 'User Groups'.

6) czkawka should be accessible at your QNAP's URl, but under port 5800 instead of 8080.

I hope this will help others...

Dominik
