### ISSUE TITLE
[Bug] Failing to play videos. Error with "gio" 

### ISSUE THREAD

**Issue by picodegalloh** [jlesage/docker-czkawka#32]
### Current Behavior

Videos failing to open. Double click or enter will not open the video in the separate player. 

This must have occurred a few updates ago. Error logs:

```
[app         ] Failed to open file /location/file.mp4, reason Launcher "gio" "open" "/location/file.mp4" failed with ExitStatus(unix_wait_status(32512))
```

I believe i have my file permissions are set up correctly. My images open fine in the console. 

### Expected Behavior

Video will open as a popup. 

### Steps To Reproduce

Search for duplicate videos or similar videos. Double click or press enter on the video file. 

### Environment

- OS: Linux
- OS version: Debian GNU/Linux 11 (bullseye) x86_64
- CPU: 11th Gen Intel i5-11400 
- Docker version: Docker version 26.1.0, build 9714adc
- Device model:
- Browser/OS: firefox 

### Container creation

```
czkawka:
    image: jlesage/czkawka
    restart: unless-stopped
    container_name: czkawka
    ports:
      - 5800:5800
    environment:
      - PUID=2001
      - PGID=2003
      - USER_ID=2001
      - GROUP_ID=2003
      - TZ=America/Los_Angeles
    volumes:
      - /srv/Configs/czkawka:/config
      - /drives/data/Media:/media
```

### Container log

```text
[app         ] Failed to open file /location/file.mp4, reason Launcher "gio" "open" "/location/file.mp4" failed with ExitStatus(unix_wait_status(32512))
```
```


### Container inspect

_No response_

### Anything else?

_No response_
